### ISSUE TITLE
As an Events Organiser, I can "View my Dashboard", so that I can create, view and manage events.

### ISSUE THREAD

**Issue by chrishigglers** [chrishigglers/Higglers#1]
Description
===============================
As an Event Organiser, I should be able to view, manage and create events from my dashboard. 

Acceptance Criteria
===============================

Acceptance Criteria 1
----------------
GIVEN that I am logged into Higglers,
WHEN I view my dashboard,
THEN I should be able to
- view all of my events, 
- manage all of my events
- create new events

Acceptance Criteria 2
----------------
GIVEN that I can view my dashboard
WHEN I look at my events
Then I can quickly see high level management information like:
- When the event is due to take place
- Number of pitches already filled
- Number of applications to review
 
Acceptance Criteria 3
----------------
GIVEN that I can view my dashboard,
WHEN I 'click' on create new event,
THEN I am taken to the page where I can create a new event.

**Comment by alexis-l8** [comment]
Events should be ordered by time till start.

**Comment by alexis-l8** [comment]
- [ ] app starts at`/login` which should enable the user to enter their username and password
    - create the react router endpoint for `/login` (*t4h*)
    - create the component for the login form (*t2h*)
- [ ] we will then hydrate our redux store with this user data. (*t4h*)
- [ ] we must then use this login information to differentiate between a trader or organiser, before showing them their respective dashboards. We will need to use cookies for authentication and session management. (create individual issue) (*t1d*)
- [ ] after successfully logging in, the user will reach`/dashboard` which should show an event organiser's dashboard information. 
    - create the react router endpoint for `/dashboard`(*t25m*)
- [ ] we then need to make a request to our backend database and fetch all the information required for this page which will initially be dummy data. 
    - create SQL queries (*t3h*)
    - making an API call to our database with the queries (*t3h*)
- [ ] we will then hydrate our redux store with this dummy data. (*t2h*)
- [ ] we then use this to display the information on the screen. The data will be displayed with no components or styling at this point.
    - extract information from the redux store (*t3h*)
    - displaying only the information needed for the `/dashboard` view (*t3h*)
- [ ] we then need to style the pages as per the invision views. 
    - header component containing user information (*t4h*)
    - events filtering component placeholder. No filtering ability (*t25m*)
    - events creation component placeholder. No ability to create new event (*t25m*)
    - event cards displaying dummy image, event_name, start_date, address_city (*t4h*)
    - "see all" component. Clicking this will show more event cards (*t2h*)

**Total time: 5.5 days**
